# -*- coding: utf-8 -*-
"""Copy of EDA - Hotel Booking .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6LZni8FouPlTKU0-Gt5FQCxBMENtjaZ
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Connecting Google Drive
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/My Drive/HotelBookingsDataset.xlsx'
hotel_data_df = pd.read_excel(path)

## Data Preprocessing

hotel_data = hotel_data_df

# Assgning the integer values of company to agent as we have no need for both in this analysis.
hotel_data['agent'] = hotel_data.apply(lambda x: x['company'] if pd.notnull(x['company']) else x['agent'], axis=1)
hotel_data.drop('company', axis=1, inplace=True)

# Check for missing values
print(hotel_data.isnull().sum())

# Dropping NULL observations
hotel_data.dropna(inplace=True)

# remove duplicates
hotel_data = hotel_data.drop_duplicates()

# Recheck for missing values
print(hotel_data.isnull().sum())


# Convert categorical variables to appropriate data types
hotel_data['arrival_date_month'] = pd.Categorical(hotel_data['arrival_date_month'], categories=[
    'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November',
    'December'], ordered=True)
hotel_data['hotel'] = pd.Categorical(hotel_data['hotel'])
hotel_data['meal'] = pd.Categorical(hotel_data['meal'])
hotel_data['market_segment'] = pd.Categorical(hotel_data['market_segment'])
hotel_data['distribution_channel'] = pd.Categorical(hotel_data['distribution_channel'])
hotel_data['reserved_room_type'] = pd.Categorical(hotel_data['reserved_room_type'])
hotel_data['assigned_room_type'] = pd.Categorical(hotel_data['assigned_room_type'])
hotel_data['deposit_type'] = pd.Categorical(hotel_data['deposit_type'])
hotel_data['customer_type'] = pd.Categorical(hotel_data['customer_type'])
hotel_data['reservation_status'] = pd.Categorical(hotel_data['reservation_status'])

# Statistical summary of numerical variables
print(hotel_data.describe())

# Explore categorical variables
categorical_vars = ['hotel', 'meal', 'market_segment', 'distribution_channel', 'reserved_room_type', 'assigned_room_type',
                    'deposit_type', 'customer_type', 'reservation_status']
for var in categorical_vars:
    print(hotel_data[var].value_counts())

# Dataset Columns
hotel_data.columns

# Dataset Describe
hotel_data.describe(include='all')

# Check Unique Values for each variable.
for i in hotel_data.columns.tolist():
  print("No. of unique values in ",i,"is",hotel_data[i].nunique(),".")

## Data Vizualization

# Distribution of lead time
plt.figure(figsize=(10, 6))
sns.histplot(hotel_data['lead_time'], bins=30, kde=True)
plt.title('Distribution of Lead Time')
plt.xlabel('Lead Time (days)')
plt.ylabel('Frequency')
plt.show()

# Distribution of stay duration
plt.figure(figsize=(10, 6))
# sns.histplot(hotel_data['stays_in_weekend_nights'] + hotel_data['stays_in_week_nights'], bins=30, kde=True)
sns.histplot(hotel_data['stays_in_weekend_nights'] + hotel_data['stays_in_week_nights'], bins=30)
plt.title('Distribution of Stay Duration')
plt.xlabel('Stay Duration (nights)')
plt.ylabel('Frequency')
plt.show()

# Distribution of booking cancellations
plt.figure(figsize=(8, 5))
sns.countplot(x='is_canceled', data=hotel_data)
plt.title('Distribution of Booking Cancellations')
plt.xlabel('Booking Canceled')
plt.ylabel('Count')
plt.show()

# Distribution of total special requests
plt.figure(figsize=(8, 5))
sns.countplot(x='total_of_special_requests', data=hotel_data)
plt.title('Distribution of Total Special Requests')
plt.xlabel('Total Special Requests')
plt.ylabel('Count')
plt.show()

# Relationship between lead time and cancellation rate
plt.figure(figsize=(10, 6))
sns.boxplot(x='is_canceled', y='lead_time', data=hotel_data)
plt.title('Relationship between Lead Time and Cancellation Rate')
plt.xlabel('Booking Canceled')
plt.ylabel('Lead Time (days)')
plt.show()

# Relationship between stay duration and hotel type
plt.figure(figsize=(10, 6))
sns.boxplot(x='hotel', y=hotel_data['stays_in_weekend_nights'] + hotel_data['stays_in_week_nights'], data=hotel_data)
plt.title('Relationship between Stay Duration and Hotel Type')
plt.xlabel('Hotel')
plt.ylabel('Stay Duration (nights)')
plt.show()

# Distribution of booking cancellations by market segment
plt.figure(figsize=(12, 6))
sns.countplot(x='market_segment', hue='is_canceled', data=hotel_data)
plt.title('Distribution of Booking Cancellations by Market Segment')
plt.xlabel('Market Segment')
plt.ylabel('Count')
plt.legend(title='Bookings vs Cancellations',labels=['Bookings','Cancellations'], loc='upper left')
plt.xticks(rotation=45)
plt.show()

# Distribution of booking cancellations by customer type
plt.figure(figsize=(10, 6))
sns.countplot(x='customer_type', hue='is_canceled', data=hotel_data)
plt.title('Distribution of Booking Cancellations by Customer Type')
plt.xlabel('Customer Type')
plt.ylabel('Count')
plt.legend(title='Bookings vs Cancellations',labels=['Bookings','Cancellations'], loc='upper right')
plt.xticks(rotation=45)
plt.show()

# Correlation heatmap between numerical variables
plt.figure(figsize=(12, 8))
sns.heatmap(hotel_data.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap between Numerical Variables')
plt.show()

# hotel_data.columns

# Boxplot of lead time by hotel type and customer type
plt.figure(figsize=(12, 8))
sns.boxplot(x='hotel', y='lead_time', hue='customer_type', data=hotel_data)
plt.title('Boxplot of Lead Time by Hotel Type and Customer Type')
plt.xlabel('Hotel')
plt.ylabel('Lead Time (days)')
plt.legend(title='Customer Type')
plt.show()

# Scatter plot of lead time vs. stay duration colored by cancellation status
plt.figure(figsize=(10, 6))
sns.scatterplot(x='lead_time', y=hotel_data['stays_in_weekend_nights'] + hotel_data['stays_in_week_nights'],
                hue='is_canceled', data=hotel_data)
plt.title('Lead Time vs. Stay Duration')
plt.xlabel('Lead Time (days)')
plt.ylabel('Stay Duration (nights)')
plt.legend(title='Booking Canceled', loc='upper right')
plt.show()